### ISSUE TITLE
Build fails with Nginx 1.0.5

### ISSUE THREAD

**Issue by omega8cc** [FRiCKLE/ngx_cache_purge#2]
1.0.5 includes fixes for critical issues related to cache and config reloads causing self-DoS, so it would be great to have this fixed:

<code>
/var/opt/ngx_cache_purge//ngx_cache_purge_module.c: In function ‘ngx_http_file_cache_purge’:
/var/opt/ngx_cache_purge//ngx_cache_purge_module.c:691: error: ‘ngx_http_file_cache_node_t’ has no member named ‘length’
make[1]: **\* [objs/addon/ngx_cache_purge/ngx_cache_purge_module.o] Error 1
make[1]: Leaving directory `/var/opt/nginx-1.0.5'
make: **\* [build] Error 2
</code>

**Comment by PiotrSikora** [comment]
It works just fine, you just need to use current version of the module (1.3).

**Comment by omega8cc** [comment]
Piotr, 1.3 is the same as master, afaik, and it doesn't work with Nginx 1.0.5. I tested it a few times, and I had to use this dirty hack to get it to build w/o errors: https://github.com/omega8cc/nginx-for-drupal/commit/5ddc793ce43e7683f8f41605296d471c8d9ef28c

**Comment by omega8cc** [comment]
This logic looks correct and should work, imo, but doesn't for 1.0.5, which is weird:

<code>
 #  if defined(nginx_version) && (nginx_version >= 1000001)
     cache->sh->size -= c->node->fs_size;
 #  else
     cache->sh->size -= (c->node->length + cache->bsize - 1) / cache->bsize;
 #  endif
</code>

**Comment by PiotrSikora** [comment]
Are you trying this on clean nginx-1.0.5 _release_ or with any additional patches / 3rd party modules? What compiler do you use?

I've double checked it few times with different compilers and it works just fine for me.

**Comment by omega8cc** [comment]
I have tried it many times on Debian Squeeze and Ubuntu Lucid/Natty on my test Linode VPS, so pretty popular setup. It is vanilla Nginx 1.0.5 _release_ with upload progress module added only: https://github.com/masterzen/nginx-upload-progress-module, and I'm using it with our Barracuda installer for Aegir/Drupal: https://github.com/omega8cc/nginx-for-drupal/blob/master/BARRACUDA.sh.txt#L2340

**Comment by PiotrSikora** [comment]
I've just build it on Ubuntu 10.10 with same `./configure` arguments and I didn't have any problems:

```
$ ./objs/nginx -V
nginx: nginx version: nginx/1.0.5
nginx: built by gcc 4.4.5 (Ubuntu/Linaro 4.4.4-14ubuntu5)
nginx: TLS SNI support enabled
nginx: configure arguments: --prefix=/usr --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf
--error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log
--pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --user=www-data --group=www-data
--with-http_realip_module --with-http_gzip_static_module --with-http_stub_status_module
--with-http_ssl_module --without-mail_pop3_module --without-mail_imap_module
--without-mail_smtp_module --without-http_ssi_module --without-http_scgi_module
--without-http_uwsgi_module --with-debug --with-ipv6
--add-module=../nginx-upload-progress-module/ --add-module=../ngx_cache_purge-1.3
```

Also, ngx_cache_purge is quite popular and usually I get few reports within first 24 hours after incompatible nginx release shows-up. This time I didn't, which just confirms that you're isolated case and it works for virtually everyone else.

Unfortunately, I don't think there is anything I can do to help you.

**Comment by omega8cc** [comment]
You are right, it is for sure Linode specific issue. I can't reproduce it on any our own system/server, while on Linode it fails always. I should test it on our own servers earlier to not waste so much time :/ I'm sorry for the trouble.

**Comment by PiotrSikora** [comment]
No worries, but you should probably talk with Linode guys and investigate why this happens, because it shouldn't.
